import React, { useState, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  ArrowLeft, 
  Download, 
  Printer, 
  FileText, 
  Activity, 
  User, 
  Calendar, 
  Thermometer, 
  Heart, 
  AlertTriangle,
  CheckCircle,
  Shield,
  Clock
} from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { useLanguage } from '../contexts/LanguageContext';

const ExportReport = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const reportRef = useRef(null);
  const [exporting, setExporting] = useState(false);
  const { t, language } = useLanguage();

  // Load patient data
  const patients = JSON.parse(localStorage.getItem('asha_patients') || '[]');
  const patient = patients.find(p => p.id === id);

  if (!patient) {
    return (
      <div className="app-layout-page">
        <Navbar />
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '4rem 2rem', gap: '1rem' }}>
          <AlertTriangle size={48} style={{ color: 'var(--color-error)' }} />
          <h3>{t('Patient Record Not Found', { hi: 'रोगी रिकॉर्ड नहीं मिला', te: 'రోగి రికార్డు కనుగొనబడలేదు' })}</h3>
          <button onClick={() => navigate('/')} className="btn-primary">{t('Back to Dashboard', { hi: 'डैशबोर्ड पर वापस जाएं', te: 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి' })}</button>
        </div>
        <Footer />
      </div>
    );
  }

  const triageResult = patient.triageResult;

  // Translation helpers
  const getTranslation = (field, lang = 'en') => {
    if (!field) return "";
    if (typeof field === 'string') return field;
    return field[lang] || field.en || "";
  };

  const getTranslationArray = (field, lang = 'en') => {
    if (!field) return [];
    if (Array.isArray(field)) return field;
    return field[lang] || field.en || [];
  };

  const getTriageLabel = (color) => {
    switch (color?.toUpperCase()) {
      case 'RED': return { label: t('IMMEDIATE EMERGENCY', {hi: 'तत्काल आपातकाल', te: 'తక్షణ అత్యవసర పరిస్థితి'}), color: '#dc2626', bg: '#fef2f2' };
      case 'ORANGE': return { label: t('VERY URGENT', {hi: 'अत्यंत जरूरी', te: 'చాలా అత్యవసరం'}), color: '#ea580c', bg: '#fff7ed' };
      case 'YELLOW': return { label: t('URGENT - STABLE', {hi: 'जरूरी - स्थिर', te: 'అత్యవసరం - స్థిరమైన'}), color: '#ca8a04', bg: '#fefce8' };
      case 'GREEN': return { label: t('NON-URGENT', {hi: 'गैर-आपातकालीन', te: 'అత్యవసరం కానిది'}), color: '#16a34a', bg: '#f0fdf4' };
      default: return { label: t('UNKNOWN', {hi: 'अज्ञात', te: 'తెలియదు'}), color: '#64748b', bg: '#f8fafc' };
    }
  };

  const triageInfo = getTriageLabel(triageResult.triageColor);
  const reportDate = new Date().toLocaleString(language === 'hi' ? 'hi-IN' : (language === 'te' ? 'te-IN' : 'en-IN'), { 
    dateStyle: 'long', 
    timeStyle: 'short' 
  });

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadText = () => {
    setExporting(true);
    
    const firstAid = getTranslationArray(triageResult.firstAidInstructions, language);
    const redFlags = getTranslationArray(triageResult.redFlags, language);
    const analysis = getTranslation(triageResult.conditionPossibilities, language);
    const summary = getTranslation(triageResult.translatedSummary, language);
    
    const reportText = `
══════════════════════════════════════════════════
       ASHATRIAGE AI — PATIENT TRIAGE REPORT
══════════════════════════════════════════════════
Report Generated: ${reportDate}
System: AshaTriage AI Clinical Decision Support
──────────────────────────────────────────────────

PATIENT INFORMATION
────────────────────
  Name:        ${patient.name}
  Patient ID:  ${patient.id}
  Age:         ${patient.age} years
  Gender:      ${patient.gender}
  Triage Date: ${patient.date}

VITAL SIGNS
────────────────────
  Temperature:   ${patient.vitals.temperature} °F
  Heart Rate:    ${patient.vitals.heartRate} bpm
  Blood Pressure: ${patient.vitals.systolic}/${patient.vitals.diastolic} mmHg

SYMPTOMS REPORTED
────────────────────
  ${patient.symptoms}

══════════════════════════════════════════════════
  TRIAGE CLASSIFICATION: ${triageResult.triageColor?.toUpperCase()}
  STATUS: ${triageInfo.label}
══════════════════════════════════════════════════

CLINICAL ANALYSIS
────────────────────
  ${analysis}

SUMMARY
────────────────────
  ${summary}

FIRST AID INSTRUCTIONS
────────────────────
${firstAid.map((s, i) => `  ${i + 1}. ${s}`).join('\n')}

RED FLAGS TO MONITOR
────────────────────
${redFlags.map((f, i) => `  ⚠ ${f}`).join('\n')}

──────────────────────────────────────────────────
DISCLAIMER: This report was generated by AshaTriage AI,
an AI-powered clinical decision support tool for ASHA 
workers. It is NOT a substitute for professional medical
diagnosis. Always consult a qualified physician for
definitive treatment decisions.
──────────────────────────────────────────────────
Emergency Ambulance: 108 | Health Helpline: 104
══════════════════════════════════════════════════
`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AshaTriage_Report_${patient.id}_${patient.date}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setTimeout(() => setExporting(false), 1200);
  };

  return (
    <div className="app-layout-page">
      <Navbar />

      <main style={{ maxWidth: '900px', margin: '0 auto', padding: '2rem 1.25rem', width: '100%' }}>
        {/* Top Actions Bar */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '0.75rem' }}>
          <button onClick={() => navigate(`/patient/${id}`)} className="btn-secondary" style={{ gap: '0.4rem' }}>
            <ArrowLeft size={16} /> {t('Back to Case File', {hi: 'केस फ़ाइल पर वापस जाएं', te: 'కేసు ఫైల్‌కు తిరిగి వెళ్లండి'})}
          </button>
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <button onClick={handleDownloadText} className="btn-primary" style={{ gap: '0.4rem' }} disabled={exporting}>
              <Download size={16} /> {exporting ? t('Exporting...', {hi: 'निर्यात हो रहा है...', te: 'ఎగుమతి అవుతోంది...'}) : t('Download Report', {hi: 'रिपोर्ट डाउनलोड करें', te: 'నివేదికను డౌన్‌లోడ్ చేయండి'})}
            </button>
            <button onClick={handlePrint} className="btn-secondary" style={{ gap: '0.4rem' }}>
              <Printer size={16} /> {t('Print', {hi: 'प्रिंट करें', te: 'ప్రింట్ చేయండి'})}
            </button>
          </div>
        </div>

        {/* Printable Report Card */}
        <div ref={reportRef} style={{
          backgroundColor: '#fff',
          borderRadius: 'var(--border-radius-lg)',
          border: '1.5px solid var(--border-light)',
          boxShadow: 'var(--shadow-lg)',
          overflow: 'hidden'
        }}>
          {/* Report Header */}
          <div style={{
            background: 'linear-gradient(135deg, #0f172a 0%, #0f4c4c 50%, #0e7490 100%)',
            padding: '2.5rem 2rem',
            color: '#fff',
            position: 'relative',
            overflow: 'hidden'
          }}>
            <div style={{ position: 'absolute', top: '-30px', right: '-30px', width: '180px', height: '180px', borderRadius: '50%', background: 'rgba(6, 182, 212, 0.12)' }} />
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
              <Activity size={28} />
              <span style={{ fontFamily: 'var(--font-display)', fontWeight: 900, fontSize: '1.5rem', letterSpacing: '-0.03em' }}>AshaTriage AI</span>
            </div>
            <h1 style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: '1.75rem', letterSpacing: '-0.03em', margin: 0 }}>
              {t('Patient Triage Report', {hi: 'रोगी ट्राइएज रिपोर्ट', te: 'రోగి ట్రయాజ్ నివేదిక'})}
            </h1>
            <p style={{ color: 'rgba(255,255,255,0.65)', fontSize: '0.9rem', marginTop: '0.25rem' }}>
              {t('Clinical Decision Support System for ASHA Workers', {hi: 'आशा कार्यकर्ताओं के लिए क्लीनिकल निर्णय सहायता प्रणाली', te: 'ASHA కార్యకర్తల కోసం క్లినికల్ డెసిషన్ సపోర్ట్ సిస్టమ్'})}
            </p>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '1rem', color: 'rgba(255,255,255,0.5)', fontSize: '0.8rem' }}>
              <Clock size={14} />
              <span>{t('Report Generated:', {hi: 'रिपोर्ट जनरेट की गई:', te: 'నివేదిక రూపొందించబడింది:'})} {reportDate}</span>
            </div>
          </div>

          {/* Triage Classification Banner */}
          <div style={{
            padding: '1.25rem 2rem',
            backgroundColor: triageInfo.bg,
            borderBottom: `3px solid ${triageInfo.color}`,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
            gap: '0.5rem'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
              <div style={{
                width: '14px', height: '14px', borderRadius: '50%',
                backgroundColor: triageInfo.color,
                boxShadow: `0 0 0 4px ${triageInfo.color}33`
              }} />
              <span style={{ fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: '1.15rem', color: triageInfo.color, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                {triageResult.triageColor} — {triageInfo.label}
              </span>
            </div>
            <Shield size={22} style={{ color: triageInfo.color }} />
          </div>

          {/* Report Body */}
          <div style={{ padding: '2rem' }}>
            {/* Patient Info Grid */}
            <div style={{ marginBottom: '2rem' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <User size={18} style={{ color: 'var(--primary-solid)' }} />
                {t('Patient Information', {hi: 'रोगी की जानकारी', te: 'రోగి సమాచారం'})}
              </h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '0.75rem' }}>
                {[
                  { label: t('Full Name', {hi: 'पूरा नाम', te: 'పూర్తి పేరు'}), value: patient.name },
                  { label: t('Patient ID', {hi: 'रोगी ID', te: 'రోగి ID'}), value: patient.id },
                  { label: t('Age', {hi: 'उम्र', te: 'వయస్సు'}), value: `${patient.age} ${t('years', {hi: 'वर्ष', te: 'సంవత్సరాలు'})}` },
                  { label: t('Gender', {hi: 'लिंग', te: 'లింగం'}), value: patient.gender === 'Male' ? t('Male', {hi: 'पुरुष', te: 'మగ'}) : patient.gender === 'Female' ? t('Female', {hi: 'महिला', te: 'ఆడ'}) : t('Other', {hi: 'अन्य', te: 'ఇతర'}) },
                  { label: t('Triage Date', {hi: 'जांच की तारीख', te: 'ట్రయాజ్ తేదీ'}), value: patient.date }
                ].map((item, idx) => (
                  <div key={idx} style={{
                    backgroundColor: 'var(--bg-base)',
                    borderRadius: 'var(--border-radius-sm)',
                    padding: '0.875rem 1rem',
                    border: '1px solid var(--border-light)'
                  }}>
                    <div style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.2rem' }}>{item.label}</div>
                    <div style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--text-primary)' }}>{item.value}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Vitals Grid */}
            <div style={{ marginBottom: '2rem' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <Thermometer size={18} style={{ color: 'var(--primary-solid)' }} />
                {t('Vital Signs', {hi: 'शारीरिक संकेत (Vitals)', te: 'జీవ సంకేతాలు'})}
              </h3>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: '0.75rem' }}>
                {[
                  { label: t('Temperature', {hi: 'तापमान', te: 'ఉష్ణోగ్రత'}), value: `${patient.vitals.temperature}°F`, icon: '🌡️' },
                  { label: t('Heart Rate', {hi: 'हृदय गति', te: 'హృదయ స్పందన రేటు'}), value: `${patient.vitals.heartRate} bpm`, icon: '❤️' },
                  { label: t('Systolic BP', {hi: 'सिस्टोलिक BP', te: 'సిస్టోలిక్ BP'}), value: `${patient.vitals.systolic} mmHg`, icon: '🩸' },
                  { label: t('Diastolic BP', {hi: 'डायस्टोलिक BP', te: 'డయాస్టోలిక్ BP'}), value: `${patient.vitals.diastolic} mmHg`, icon: '🩸' }
                ].map((item, idx) => (
                  <div key={idx} style={{
                    backgroundColor: 'var(--bg-base)',
                    borderRadius: 'var(--border-radius-sm)',
                    padding: '1rem',
                    border: '1px solid var(--border-light)',
                    textAlign: 'center'
                  }}>
                    <div style={{ fontSize: '1.5rem', marginBottom: '0.25rem' }}>{item.icon}</div>
                    <div style={{ fontFamily: 'var(--font-display)', fontSize: '1.3rem', fontWeight: 800, color: 'var(--text-primary)' }}>{item.value}</div>
                    <div style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{item.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Symptoms */}
            <div style={{ marginBottom: '2rem' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <FileText size={18} style={{ color: 'var(--primary-solid)' }} />
                {t('Symptoms Reported', {hi: 'दर्ज किए गए लक्षण', te: 'నమోదైన లక్షణాలు'})}
              </h3>
              <div style={{
                backgroundColor: 'var(--bg-base)',
                border: '1px solid var(--border-light)',
                borderRadius: 'var(--border-radius-sm)',
                padding: '1.25rem',
                fontSize: '0.95rem',
                color: 'var(--text-secondary)',
                lineHeight: '1.6',
                fontStyle: 'italic'
              }}>
                "{patient.symptoms}"
              </div>
            </div>

            {/* Clinical Analysis */}
            <div style={{ marginBottom: '2rem' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <Activity size={18} style={{ color: 'var(--primary-solid)' }} />
                {t('Clinical Analysis', {hi: 'क्लीनिकल विश्लेषण', te: 'క్లినికల్ విశ్లేషణ'})}
              </h3>
              <p style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', lineHeight: '1.7' }}>
                {getTranslation(triageResult.conditionPossibilities, language)}
              </p>
            </div>

            {/* First Aid Instructions */}
            <div style={{ marginBottom: '2rem' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.1rem', color: 'var(--triage-green-text)', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <CheckCircle size={18} />
                {t('First Aid Instructions', {hi: 'प्राथमिक उपचार के निर्देश', te: 'ప్రథమ చికిత్స సూచనలు'})}
              </h3>
              <ol style={{ paddingLeft: '1.5rem', margin: 0 }}>
                {getTranslationArray(triageResult.firstAidInstructions, language).map((step, idx) => (
                  <li key={idx} style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', lineHeight: '1.6', marginBottom: '0.5rem', paddingLeft: '0.25rem' }}>{step}</li>
                ))}
              </ol>
            </div>

            {/* Red Flags */}
            <div style={{ marginBottom: '1.5rem' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.1rem', color: 'var(--color-error)', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <AlertTriangle size={18} />
                {t('Critical Red Flags', {hi: 'गंभीर चेतावनी के लक्षण (Red Flags)', te: 'క్లిష్టమైన ఎరుపు జెండాలు (Red Flags)'})}
              </h3>
              <ul style={{ paddingLeft: '1.5rem', margin: 0 }}>
                {getTranslationArray(triageResult.redFlags, language).map((flag, idx) => (
                  <li key={idx} style={{ fontSize: '0.95rem', color: 'var(--color-error)', lineHeight: '1.6', marginBottom: '0.4rem' }}>
                    {flag}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Report Footer */}
          <div style={{
            padding: '1.5rem 2rem',
            backgroundColor: 'var(--bg-base)',
            borderTop: '1px solid var(--border-light)',
            display: 'flex',
            flexDirection: 'column',
            gap: '0.75rem'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem', color: 'var(--color-warning)', fontWeight: 600 }}>
              <AlertTriangle size={14} />
              {t('DISCLAIMER: This report is generated by an AI clinical decision support tool. Not a substitute for professional medical diagnosis.', {hi: 'अस्वीकरण: यह रिपोर्ट एआई टूल द्वारा जनरेट की गई है। यह पेशेवर चिकित्सा निदान का विकल्प नहीं है।', te: 'నిరాకరణ: ఈ నివేదిక AI క్లినికల్ డెసిషన్ సపోర్ట్ టూల్ ద్వారా రూపొందించబడింది. ప్రొఫెషనల్ మెడికల్ డయాగ్నసిస్‌కు ప్రత్యామ్నాయం కాదు.'})}
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '0.5rem' }}>
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                🚑 {t('Emergency Ambulance:', {hi: 'आपातकालीन एम्बुलेंस:', te: 'అత్యవసర అంబులెన్స్:'})} <strong>108</strong> &nbsp;|&nbsp; 🏥 {t('Health Helpline:', {hi: 'स्वास्थ्य हेल्पलाइन:', te: 'ఆరోగ్య హెల్ప్‌లైన్:'})} <strong>104</strong>
              </span>
              <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                AshaTriage AI v1.0 • Powered by Gemini AI
              </span>
            </div>
          </div>
        </div>
      </main>

      <Footer />

      {/* Print Styles */}
      <style>{`
        @media print {
          .navbar-header, .footer-layout, .btn-primary, .btn-secondary {
            display: none !important;
          }
          .app-layout-page {
            background: #fff !important;
          }
          main {
            padding: 0 !important;
            max-width: 100% !important;
          }
        }
      `}</style>
    </div>
  );
};

export default ExportReport;
